/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.AddressDetails;
import Profile.BankDetails;
import Profile.DrivingLicense;
import Profile.MedicalRecordDetails;
import Profile.PersonalDetails;
import javax.swing.ImageIcon;

/**
 *
 * @author krish
 */
public class ViewProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPersonalInformation
     */
    
    
    public ViewProfilePanel(AddressDetails addressDetails,BankDetails bankDetails,DrivingLicense drivingLicense, MedicalRecordDetails medicalRecordDetails, PersonalDetails personalDetails) {
        initComponents();
        displayProfile(addressDetails,bankDetails,drivingLicense,medicalRecordDetails,personalDetails);
    }
    
    
    
    private void displayProfile(AddressDetails addressDetails,BankDetails bankDetails,DrivingLicense drivingLicense, MedicalRecordDetails medicalRecordDetails, PersonalDetails personalDetails){
        
        
        firstName.setText(personalDetails.getFirstName());
        lastName.setText(personalDetails.getLastName());
        phoneNumber.setText(personalDetails.getPhoneNumber());
        ssn.setText(personalDetails.getSsn());
        dateOfBirth.setText(personalDetails.getDateOfBirth());
        age.setText(personalDetails.getAge());
        weight.setText(personalDetails.getHeight());
        height.setText(personalDetails.getWeight());
        street.setText(addressDetails.getStreet());
        city.setText(addressDetails.getCity());
        state.setText(addressDetails.getState());
        zipcode.setText(addressDetails.getZipcode());
        account1.setText(bankDetails.getAccount1());
        account2.setText(bankDetails.getAccount2());
        accountType1.setSelectedItem(bankDetails.getAccountType1());
        accountType2.setSelectedItem(bankDetails.getAccountType2());
        balance1.setText(bankDetails.getBalance1());
        balance2.setText(bankDetails.getBalance2());
        bankName1.setText(bankDetails.getBankName1());
        bankName2.setText(bankDetails.getBankName2());
        routing1.setText(bankDetails.getRouting1());
        routing2.setText(bankDetails.getRouting2());
        medicalRecord.setText(medicalRecordDetails.getMedicalRecord());
        alergy1.setText(medicalRecordDetails.getAlergy1());
        alergy2.setText(medicalRecordDetails.getAlergy2());
        alergy3.setText(medicalRecordDetails.getAlergy3());
        licenseNumber.setText(drivingLicense.getLicenseNumber());
        dOI.setText(drivingLicense.getDateOfIssue());
        dOE.setText(drivingLicense.getDateOfExpiry());
        bloodGroup.setText(drivingLicense.getBloodGroup());
        
        String imgPth = drivingLicense.getFilePath();
        ImageIcon iconImg = new ImageIcon(imgPth);
        pic.setIcon(iconImg);
        
        
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        zipcode = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        bankName1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        accountType1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        balance1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        account1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        routing1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pic = new javax.swing.JLabel();
        licenseNumber = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        dOII1 = new javax.swing.JLabel();
        dOI = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        dOE = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        bloodGroup = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        medicalRecord = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        alergy1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        alergy2 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        alergy3 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        bankName2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        accountType2 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        balance2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        account2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        routing2 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First Name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 77, -1));

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        jPanel2.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 142, -1));

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel2.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 142, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Phone Number :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 15, 94, -1));

        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        jPanel2.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 142, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 15, 77, -1));

        dateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateOfBirthActionPerformed(evt);
            }
        });
        jPanel2.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 45, 142, -1));

        ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnActionPerformed(evt);
            }
        });
        jPanel2.add(ssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 142, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("<html>\nDate Of Birth &nbsp&nbsp&nbsp&nbsp:<br>\n(MM/DD/YYYY) \n</html>");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 100, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Age :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 15, 43, -1));

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 76, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("SSN :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 42, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("<html>\nHeight&nbsp&nbsp&nbsp&nbsp:<br>\n(in cm)\n</html>");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 77, -1));

        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });
        jPanel2.add(height, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 45, 142, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("<html>\nWeight&nbsp&nbsp&nbsp&nbsp:<br>\n(in pounds)\n<html>");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 94, -1));

        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel2.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 45, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1020, 90));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-name-40 (1).png"))); // NOI18N
        jLabel1.setText("View A Personal Profile");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Street :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 42, -1));

        street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetActionPerformed(evt);
            }
        });
        jPanel4.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 770, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("City :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 42, -1));

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel4.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 45, 199, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("State :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 49, -1));

        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        jPanel4.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 45, 252, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Zipcode :");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 55, -1));

        zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeActionPerformed(evt);
            }
        });
        jPanel4.add(zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 45, 130, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1020, 90));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("1. General Information");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 221, 29));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1020, 40));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Bank Name :");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 77, -1));

        bankName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankName1ActionPerformed(evt);
            }
        });
        jPanel7.add(bankName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 198, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Account Type :");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 15, 86, -1));

        accountType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Saving" }));
        jPanel7.add(accountType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 102, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Balance : ");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 15, 94, -1));

        balance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balance1ActionPerformed(evt);
            }
        });
        jPanel7.add(balance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 161, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Account # :");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 66, -1));

        account1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account1ActionPerformed(evt);
            }
        });
        jPanel7.add(account1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 45, 198, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Rounting # :");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 76, -1));

        routing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routing1ActionPerformed(evt);
            }
        });
        jPanel7.add(routing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 45, 219, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1020, 80));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("2. Address Information");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 221, 29));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1020, 40));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 400, 120));

        licenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberActionPerformed(evt);
            }
        });
        jPanel9.add(licenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("License No. :");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 77, -1));

        dOII1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dOII1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dOII1.setText("Date Of  Issue :");
        jPanel9.add(dOII1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 86, -1));
        jPanel9.add(dOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 45, 130, -1));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText("Date Of Epiry :");
        jPanel9.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 88, -1));

        dOE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dOEActionPerformed(evt);
            }
        });
        jPanel9.add(dOE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 161, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("Blood Group :");
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 83, -1));

        bloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupActionPerformed(evt);
            }
        });
        jPanel9.add(bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 115, 55, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1020, 150));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("Medical Record # :");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 107, -1));

        medicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRecordActionPerformed(evt);
            }
        });
        jPanel10.add(medicalRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 715, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Alergy 1 :");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 59, -1));

        alergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy1ActionPerformed(evt);
            }
        });
        jPanel10.add(alergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 177, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Alergy 2 :");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 60, -1));

        alergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy2ActionPerformed(evt);
            }
        });
        jPanel10.add(alergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 45, 178, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("Alergy 3 :");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 63, -1));

        alergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy3ActionPerformed(evt);
            }
        });
        jPanel10.add(alergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 45, 204, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1020, 90));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("3. Bank Account Information");
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 221, 29));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1020, 40));

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel41.setText("5. Medical Information");
        jPanel12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 221, 29));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1020, 40));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(bankName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 198, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Bank Name :");
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 77, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Account Type :");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 15, 86, -1));

        accountType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Saving" }));
        jPanel13.add(accountType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 102, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Balance :");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 15, 94, -1));
        jPanel13.add(balance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 161, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Account # :");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 66, -1));
        jPanel13.add(account2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 198, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Rounting # :");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 45, 76, -1));
        jPanel13.add(routing2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 219, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1020, 70));

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(153, 153, 153)));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel50.setText("4. Driving License Information");
        jPanel14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 221, 29));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1020, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnActionPerformed

    private void dateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateOfBirthActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void zipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeActionPerformed

    private void bankName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankName1ActionPerformed

    private void balance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balance1ActionPerformed

    private void account1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account1ActionPerformed

    private void routing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routing1ActionPerformed

    private void alergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy3ActionPerformed

    private void alergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy2ActionPerformed

    private void alergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy1ActionPerformed

    private void medicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalRecordActionPerformed

    private void licenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumberActionPerformed

    private void dOEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dOEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dOEActionPerformed

    private void bloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account1;
    private javax.swing.JTextField account2;
    private javax.swing.JComboBox<String> accountType1;
    private javax.swing.JComboBox<String> accountType2;
    private javax.swing.JTextField age;
    private javax.swing.JTextField alergy1;
    private javax.swing.JTextField alergy2;
    private javax.swing.JTextField alergy3;
    private javax.swing.JTextField balance1;
    private javax.swing.JTextField balance2;
    private javax.swing.JTextField bankName1;
    private javax.swing.JTextField bankName2;
    private javax.swing.JTextField bloodGroup;
    private javax.swing.JTextField city;
    private javax.swing.JTextField dOE;
    private javax.swing.JTextField dOI;
    private javax.swing.JLabel dOII1;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField licenseNumber;
    private javax.swing.JTextField medicalRecord;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JLabel pic;
    private javax.swing.JTextField routing1;
    private javax.swing.JTextField routing2;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField state;
    private javax.swing.JTextField street;
    private javax.swing.JTextField weight;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables
}
